### ISSUE TITLE
Output to standard input

### ISSUE THREAD

**Issue by dangayle** [paulhammond/webkit2png#4]
Is it possible to create this so that the files/filenames(s) are returned via standard input?

For example:

<pre>webkit2png http://apple.com -F | lp -</pre>

prints:

<pre>Fetching http://apple.com ...
 ... done</pre>

:(

**Comment by paulhammond** [comment]
I think a future version of webkit2png is going to change the command line so you specify the filename yourself, instead of having webkit2png calculate it for you.

If we do that you won't need to have it return them. I'm tracking that over in #109. I think that means we can close this? If not please reopen with more details.
